version: 2

project_name: cardman

before:
  hooks:
    - go mod tidy

env:
  - GO111MODULE=on

builds:
  - id: linux-amd64
    main: ./cmd/main.go
    binary: cardman
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser

  - id: linux-arm64
    main: ./cmd/main.go
    binary: cardman
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser

  - id: darwin-amd64
    main: ./cmd/main.go
    binary: cardman
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser

  - id: darwin-arm64
    main: ./cmd/main.go
    binary: cardman
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: "cardman_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Improvements"
      regexp: "^.*improvement[(\\w)]*:+.*$"
      order: 300
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: laiambryant
    name: tui-cardman
  draft: false
  prerelease: auto
