CREATE TABLE IF NOT EXISTS BUTTON_CONFIGURATION(
  ID INTEGER PRIMARY_KEY AUTOINCREMENT,
  USER_ID INTEGER REFERENCES USERS(id),
  CONFIGURATION TEXT NOT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_BUTTON_CONFIGURATION_USER_ID ON BUTTON_CONFIGURATION(USER_ID);

